import tkinter as tk

def saludar():
    nombre = entrada_nombre.get()
    edad = entrada_edad.get()
    etiqueta_resultado.config(text=f"Hola {nombre}, tienes {edad} años.")
ventana = tk.Tk()
ventana.title("Saludo y Edad")
ventana.geometry("400x250")
ventana.configure(bg="gray")
etiqueta_nombre = tk.Label(ventana, text="Ingresa tu nombre:", bg="gray")
etiqueta_nombre.pack()
entrada_nombre = tk.Entry(ventana)
entrada_nombre.pack()
etiqueta_edad = tk.Label(ventana, text="Ingresa tu edad:", bg="gray")
etiqueta_edad.pack()
entrada_edad = tk.Entry(ventana)
entrada_edad.pack()
boton = tk.Button(ventana, text="Mostrar Saludo", command=saludar)
boton.pack()
etiqueta_resultado = tk.Label(ventana, text="", bg="gray")
etiqueta_resultado.pack()
firma = tk.Label(ventana, text="Gael Martínez Soto", fg="gray", bg="gray")
firma.place(relx=1.0, rely=1.0, x=-10, y=-10, anchor="se")
ventana.mainloop()
